// Code generated by mfd-generator v0.4.0; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

var Columns = struct {
	Message struct {
		ID, Text string
	}
}{
	Message: struct {
		ID, Text string
	}{
		ID:   "messageId",
		Text: "text",
	},
}

var Tables = struct {
	Message struct {
		Name, Alias string
	}
}{
	Message: struct {
		Name, Alias string
	}{
		Name:  "messages",
		Alias: "t",
	},
}

type Message struct {
	tableName struct{} `pg:"messages,alias:t,discard_unknown_columns"`

	ID   int    `pg:"messageId,pk"`
	Text string `pg:"text,use_zero"`
}
